### ISSUE TITLE
Fail to grab github.com/hashicorp/hcl/v2

### ISSUE THREAD

**Issue by bnm22** [tmccombs/hcl2json#8]
Looks like the latest commit is using a bad url for the hcl dependency.

`
[2020-03-20T06:23:29.632Z] package github.com/hashicorp/hcl/v2: cannot find package "github.com/hashicorp/hcl/v2" in any of:
[2020-03-20T06:23:29.632Z] 	/usr/local/go/src/github.com/hashicorp/hcl/v2 (from $GOROOT)
[2020-03-20T06:23:29.632Z] 	/go/src/github.com/hashicorp/hcl/v2 (from $GOPATH)
[2020-03-20T06:23:29.632Z] package github.com/hashicorp/hcl/v2/hclsyntax: cannot find package "github.com/hashicorp/hcl/v2/hclsyntax" in any of:
[2020-03-20T06:23:29.632Z] 	/usr/local/go/src/github.com/hashicorp/hcl/v2/hclsyntax (from $GOROOT)
[2020-03-20T06:23:29.632Z] 	/go/src/github.com/hashicorp/hcl/v2/hclsyntax (from $GOPATH)
`

**Comment by tmccombs** [comment]
it builds successfully for me, and on travis. do you have any more specific directions on how to reproduce?

**Comment by overlordchin** [comment]
I am seeing the same issue calling go get on your repo.
go get -u -v github.com/tmccombs/hcl2json
github.com/tmccombs/hcl2json (download)
github.com/hashicorp/hcl (download)
package github.com/hashicorp/hcl/v2: cannot find package "github.com/hashicorp/hcl/v2"

**Comment by tmccombs** [comment]
> github.com/hashicorp/hcl

hmm, it's supposed to be using github.com/hashicorp/hcl/v2 (https://github.com/hashicorp/hcl/wiki/Version-Selection). Does someone with more experience with go know what is going on here?  go.mod is telling it to use hcl/v2.

**Comment by overlordchin** [comment]
found a similar issue in a diff project: https://github.com/tiramiseb/terraform-provider-gandi/issues/21

"Okay, after digging a little bit, I've found this:

If your project is not using Go Modules mode, the Go toolchain will only be able to select the latest commit from the master branch, which is HCL 1 currently. There is no way to automatically install HCL 2 in "GOPATH mode".

If you want to import in another package, I guess you are not using Go Modules, that's because you cannot install HCL 2, and that's because you cannot install terraform-provider-gandi; which indirectly depends on it. In that case, the solution is to use Go Modules.

If you just want to compile it, clone the repository and use make or go build..."

**Comment by angrycub** [comment]
I was able to install using `GO111MODULE=on go get github.com/tmccombs/hcl2json` as a workaround to install even though my configuration still uses GOPATH mode.
